import type { Project } from "@/types";

export const projects: Project[] = [
  {
    id: "1",
    name: "Villa Moderna",
    description:
      "Una splendida villa moderna caratterizzata da linee pulite, ampie pareti vetrate e una connessione perfetta con il paesaggio circostante. Lo spazio abitativo open-plan è perfetto per intrattenere.",
    image: "https://placehold.co/600x400.png",
    status: "Completato",
    location: "Malibu, California",
    startDate: "2022-06-01",
    endDate: "2023-05-15",
    isPublic: true,
    classification: "Privato",
    category: "Residenziale",
    typology: "Villa",
    intervention: "Nuova Costruzione",
    client: "Cliente Privato",
    service: "Progettazione completa",
    amount: 2500000,
    works: ["Design Strutturale", "Interior Design"],
  },
  {
    id: "2",
    name: "Grattacielo Urbano",
    description:
      "Una nuova icona nello skyline della città, questo grattacielo combina un design innovativo con pratiche di costruzione sostenibili. Offre un mix di spazi residenziali e commerciali.",
    image: "https://placehold.co/600x400.png",
    status: "In Corso",
    location: "New York, New York",
    startDate: "2021-01-10",
    endDate: "2025-12-01",
    isPublic: true,
    classification: "Commerciale",
    category: "Uffici",
    typology: "Grattacielo",
    intervention: "Nuova Costruzione",
    client: "Mega Corp",
    service: "Architettura e Ingegneria",
    amount: 300000000,
    works: ["Studi di fattibilità", "Costruzione Torre"],
  },
  {
    id: "3",
    name: "Baita Ecologica",
    description:
      "Immersa nella foresta, questa baita è costruita interamente con materiali sostenibili e progettata per avere un impatto ambientale minimo, con pannelli solari e raccolta dell'acqua piovana.",
    image: "https://placehold.co/600x400.png",
    status: "Completato",
    location: "Asheville, North Carolina",
    startDate: "2022-01-20",
    endDate: "2022-09-20",
    isPublic: true,
    classification: "Privato",
    category: "Residenziale",
    typology: "Baita",
    intervention: "Costruzione Sostenibile",
    client: "Famiglia Green",
    service: "Progettazione e Costruzione",
    amount: 450000,
    works: ["Installazione pannelli solari", "Sistema raccolta acqua"],
  },
  {
    id: "4",
    name: "Concetto di Città Galleggiante",
    description:
      "Un concetto visionario per una città galleggiante sostenibile, progettata per adattarsi all'innalzamento del livello del mare. Il progetto esplora nuove forme di vita urbana e architettura modulare.",
    image: "https://placehold.co/600x400.png",
    status: "Concettuale",
    location: "Oceano Pacifico",
    startDate: "2039-01-01",
    endDate: "2040-01-01",
    isPublic: false,
    classification: "Ricerca",
    category: "Urbanistica",
    typology: "Prototipo",
    intervention: "Design Concettuale",
    client: "Fondazione Oceanica",
    service: "Ricerca e Sviluppo",
    amount: 10000000,
    works: ["Design modulare", "Studio idrodinamico"],
  },
    {
    id: "5",
    name: "Museo del Patrimonio",
    description:
      "Un restauro sensibile e un'estensione di un edificio storico per creare un museo moderno. Il design rispetta l'architettura originale fornendo allo stesso tempo spazi espositivi contemporanei.",
    image: "https://placehold.co/600x400.png",
    status: "Completato",
    location: "Kyoto, Japan",
    startDate: "2022-03-15",
    endDate: "2024-02-10",
    isPublic: true,
    classification: "Ente pubblico",
    category: "Culturale",
    typology: "Museo",
    intervention: "Restauro",
    client: "Città di Kyoto",
    service: "Restauro e Ampliamento",
    amount: 15000000,
    works: ["Restauro facciata storica", "Allestimento nuove gallerie"],
  },
  {
    id: "6",
    name: "Centro Sportivo Comunitario",
    description:
      "Una struttura sportiva polivalente progettata per essere il cuore della comunità. Il progetto è attualmente in fase strutturale e il completamento è previsto per il prossimo anno.",
    image: "https://placehold.co/600x400.png",
    status: "In Corso",
    location: "Manchester, UK",
    startDate: "2023-09-01",
    endDate: "2025-08-30",
    isPublic: false,
    classification: "Ente pubblico",
    category: "Sportivo",
    typology: "Centro Comunitario",
    intervention: "Nuova Costruzione",
    client: "Comune di Manchester",
    service: "Progettazione e Direzione Lavori",
    amount: 8000000,
    works: ["Costruzione campo da calcio", "Realizzazione piscina olimpionica"],
  },
];
