
'use client';

import { collection, doc, writeBatch } from 'firebase/firestore';
import { db } from './firebase';
import type { Project } from '@/types';

const projectsData: Omit<Project, 'id'>[] = [
    {
        name: "Intervento di riparazione e rafforzamento locale per la vulnerabilità sismica della Chiesa di Santa Maria Assunta",
        image: "https://placehold.co/600x400.png",
        location: "Fornelli (IS)",
        startDate: "2013-01-01",
        endDate: "2013-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI ISERNIA - VENAFRO",
        service: "Progettazione definitiva, esecutiva e D.LL.",
        amount: 530000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di riparazione e rafforzamento locale per la vulnerabilità sismica della Chiesa di San Michele Arcangelo",
        image: "https://placehold.co/600x400.png",
        location: "Castelpetroso (IS)",
        startDate: "2013-01-01",
        endDate: "2013-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI CAMPOBASSO - BOJANO",
        service: "Progettazione definitiva, esecutiva e D.LL.",
        amount: 250000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di riparazione e rafforzamento locale per la vulnerabilità sismica della Chiesa di San Silvestro Papa",
        image: "https://placehold.co/600x400.png",
        location: "Bagnoli del Trigno (IS)",
        startDate: "2013-01-01",
        endDate: "2013-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI TRIVENTO",
        service: "Progettazione definitiva, esecutiva e D.LL.",
        amount: 400000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di riparazione e rafforzamento locale per la vulnerabilità sismica della Chiesa di Santa Maria delle Grazie",
        image: "https://placehold.co/600x400.png",
        location: "Toro (CB)",
        startDate: "2014-01-01",
        endDate: "2014-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI CAMPOBASSO - BOJANO",
        service: "Progettazione definitiva, esecutiva e D.LL.",
        amount: 400000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di miglioramento sismico della Chiesa e Campanile di Santa Maria Maggiore",
        image: "https://placehold.co/600x400.png",
        location: "Busso (CB)",
        startDate: "2015-01-01",
        endDate: "2015-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI CAMPOBASSO - BOJANO",
        service: "Progettazione definitiva, esecutiva e D.LL.",
        amount: 700000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di riparazione e rafforzamento locale per la vulnerabilità sismica della Chiesa del SS. Salvatore",
        image: "https://placehold.co/600x400.png",
        location: "Monacilioni (CB)",
        startDate: "2015-01-01",
        endDate: "2015-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI CAMPOBASSO - BOJANO",
        service: "Progettazione definitiva, esecutiva e D.LL.",
        amount: 200000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di consolidamento e restauro della Chiesa Cattedrale di Trivento",
        image: "https://placehold.co/600x400.png",
        location: "Trivento (CB)",
        startDate: "2016-01-01",
        endDate: "2016-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI TRIVENTO",
        service: "Progettazione esecutiva e D.LL.",
        amount: 2000000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di consolidamento e restauro del complesso monumentale dell'Episcopio",
        image: "https://placehold.co/600x400.png",
        location: "Trivento (CB)",
        startDate: "2016-01-01",
        endDate: "2016-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI TRIVENTO",
        service: "Progettazione esecutiva e D.LL.",
        amount: 1000000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Progetto di recupero e valorizzazione del complesso edilizio dell'ex-convento dei Cappuccini",
        image: "https://placehold.co/600x400.png",
        location: "Trivento (CB)",
        startDate: "2016-01-01",
        endDate: "2016-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "COMUNE DI TRIVENTO",
        service: "Progettazione definitiva ed esecutiva",
        amount: 1000000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di riparazione e rafforzamento locale per la vulnerabilità sismica della Chiesa di Santa Maria della Strada",
        image: "https://placehold.co/600x400.png",
        location: "Matrice (CB)",
        startDate: "2016-01-01",
        endDate: "2016-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI CAMPOBASSO - BOJANO",
        service: "Progettazione esecutiva e D.LL.",
        amount: 600000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di adeguamento dell'immobile comunale \"Casa del Pellegrino\" da adibire a struttura di accoglienza",
        image: "https://placehold.co/600x400.png",
        location: "Castelpetroso (IS)",
        startDate: "2017-01-01",
        endDate: "2017-12-31",
        classification: "",
        category: "E.06 - Edifici e complessi a carattere collettivo",
        typology: "",
        intervention: "",
        client: "COMUNE DI CASTELPETROSO",
        service: "Progettazione esecutiva, coordinamento sicurezza in fase di progettazione",
        amount: 1500000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di recupero e valorizzazione del complesso edilizio dell'ex-convento dei Cappuccini - 2° lotto",
        image: "https://placehold.co/600x400.png",
        location: "Trivento (CB)",
        startDate: "2017-01-01",
        endDate: "2017-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "COMUNE DI TRIVENTO",
        service: "Progettazione esecutiva e D.LL.",
        amount: 500000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di miglioramento sismico della Chiesa di Santa Maria Assunta",
        image: "https://placehold.co/600x400.png",
        location: "San Giuliano di Puglia (CB)",
        startDate: "2017-01-01",
        endDate: "2017-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI LARINO - TERMOLI",
        service: "Progettazione esecutiva e D.LL.",
        amount: 600000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di consolidamento e restauro del prospetto principale della Chiesa Cattedrale di Larino",
        image: "https://placehold.co/600x400.png",
        location: "Larino (CB)",
        startDate: "2017-01-01",
        endDate: "2017-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI LARINO - TERMOLI",
        service: "Progettazione esecutiva e D.LL.",
        amount: 1000000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Restauro e risanamento conservativo dell'ex Episcopio di Sepino",
        image: "https://placehold.co/600x400.png",
        location: "Sepino (CB)",
        startDate: "2018-01-01",
        endDate: "2018-12-31",
        classification: "",
        category: "E.22 - Edifici di culto",
        typology: "",
        intervention: "",
        client: "DIOCESI DI CAMPOBASSO - BOJANO",
        service: "Progettazione esecutiva e D.LL.",
        amount: 1000000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Intervento di adeguamento sismico della scuola dell'infanzia di Via D'Amato",
        image: "https://placehold.co/600x400.png",
        location: "Campobasso (CB)",
        startDate: "2019-01-01",
        endDate: "2019-12-31",
        classification: "",
        category: "E.07 - Edifici scolastici",
        typology: "",
        intervention: "",
        client: "COMUNE DI CAMPOBASSO",
        service: "Progettazione esecutiva, coordinamento sicurezza in fase di progettazione ed esecuzione e D.LL.",
        amount: 700000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di \"Recupero e Valorizzazione dell'area di S. GIOVANNIELLO, realizzazione di un centro visita ed annesso ostello diffuso, di un info-point, di un'area pic-nic, di un percorso di accesso al sito archeologico e di un parcheggio\",",
        image: "https://placehold.co/600x400.png",
        location: "Campochiaro (CB)",
        startDate: "2020-01-01",
        endDate: "2020-12-31",
        classification: "",
        category: "E.06 - Edifici e complessi a carattere collettivo",
        typology: "",
        intervention: "",
        client: "COMUNE DI CAMPOCHIARO",
        service: "Progettazione esecutiva, coordinamento sicurezza in fase di progettazione ed esecuzione e D.LL.",
        amount: 2500000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di adeguamento e miglioramento sismico, riqualificazione ed efficientamento energetico dell'edificio scolastico di Via De Sanctis",
        image: "https://placehold.co/600x400.png",
        location: "Baranello (CB)",
        startDate: "2021-01-01",
        endDate: "2021-12-31",
        classification: "",
        category: "E.07 - Edifici scolastici",
        typology: "",
        intervention: "",
        client: "COMUNE DI BARANELLO",
        service: "Progettazione esecutiva",
        amount: 2280000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    },
    {
        name: "Lavori di recupero dell'edificio ex scuola elementare da destinare a \"CASA DELLA CULTURA\"",
        image: "https://placehold.co/600x400.png",
        location: "Pietracupa (CB)",
        startDate: "2022-01-01",
        endDate: "2022-12-31",
        classification: "",
        category: "E.06 - Edifici e complessi a carattere collettivo",
        typology: "",
        intervention: "",
        client: "COMUNE DI PIETRACUPA",
        service: "Progettazione esecutiva e D.LL.",
        amount: 490000,
        status: "Completato",
        works: [],
        description: "",
        isPublic: true
    }
];

export async function seedProjects() {
    const projectsCollectionRef = collection(db, 'projects');
    const batch = writeBatch(db);

    projectsData.forEach(project => {
        // Firestore generates ID automatically when using collection().doc()
        const docRef = doc(projectsCollectionRef); 
        
        // Ensure all fields from the Project type are present
        const projectToSave: Omit<Project, 'id'> = {
            name: project.name || "",
            image: project.image || "https://placehold.co/600x400.png",
            location: project.location || "",
            startDate: project.startDate || new Date().toISOString().split('T')[0],
            endDate: project.endDate || new Date().toISOString().split('T')[0],
            classification: project.classification || "",
            category: project.category || "",
            typology: project.typology || "",
            intervention: project.intervention || "",
            client: project.client || "",
            service: project.service || "",
            amount: project.amount || 0,
            status: project.status || "Da fare",
            works: project.works || [],
            description: project.description || "",
            isPublic: project.isPublic === undefined ? true : project.isPublic,
        };
        batch.set(docRef, projectToSave);
    });

    try {
        await batch.commit();
        console.log('Successfully seeded projects!');
    } catch (error) {
        console.error('Error seeding projects:', error);
    }
}

    
