
'use client';

import { collection, doc, writeBatch } from 'firebase/firestore';
import { db } from './firebase';
import type { Project } from '@/types';

const projectsData: Omit<Project, 'id'>[] = [
    {
        name: "INTERVENTI DI SICUREZZA SISMICA DELLA CHIESA DI S.MARTINO",
        location: "Castel San Vincenzo (IS)",
        startDate: "2025-04-01",
        endDate: "2025-04-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo e D.L.",
        amount: 410000,
        category: "E.22",
        image: "https://placehold.co/600x400.png",
        status: "In Corso",
        works: [
            "Rifacimento copertura Campanile",
            "Rifacimento lattonerie (pluviali e discendenti)",
            "Rifacimento impianti e luci campate",
            "Accessibilità scale"
        ],
        description: "Analisi e Ricerca",
        classification: "Enti pubblici",
        typology: "Chiesa",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "INTERVENTI DI SICUREZZA SISMICA DEL CAMPANILE E CHIESA DELL'ASSUNZIONE MARIA VERGINE",
        location: "Castelnuovo (IS)",
        startDate: "2025-04-01",
        endDate: "2025-04-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo e D.L.",
        amount: 530000,
        category: "E.22",
        image: "https://placehold.co/600x400.png",
        status: "Da fare",
        works: [
            "Rifacimento copertura Chiesa e Campanile",
            "Consolidamento strutturale"
        ],
        description: "Da scrivere: 2° Lotto Funzionale Campanile.",
        classification: "Enti pubblici",
        typology: "Chiesa",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "RIFACIMENTO DEL MANTO DI COPERTURA DELLA CHIESA DI SANTA MARIA ASSUNTA",
        location: "Carpinone (IS)",
        startDate: "2024-10-01",
        endDate: "2024-10-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo e D.L.",
        amount: 205957.60,
        category: "E.22",
        image: "https://placehold.co/600x400.png",
        status: "In Corso",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Chiesa",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "INTERVENTI DI RIMOZIONE DELLE BARRIERE ARCHITETTONICHE E COGNITIVE NEL MUSEO DI PALAZZO PISTILLI",
        location: "Campobasso",
        startDate: "2024-08-02",
        endDate: "2024-08-02",
        client: "Parco Archeologico di Sepino e Direzione Regionale Musei Molise",
        service: "Progetto di Fattibilità Tecnica ed Economica, Progetto esecutivo, C.S.P.",
        amount: 55000,
        category: "E.21",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Museo",
        intervention: "Interni",
        isPublic: true
    },
    {
        name: "INTERVENTI DI SICUREZZA SISMICA DELLA CHIESA E CAMPANILE DI SANTA MARIA DELL’ASSUNTA",
        location: "Rocchetta a Volturno (IS)",
        startDate: "2024-07-01",
        endDate: "2024-07-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo, D.L., C.S.E.",
        amount: 520000,
        category: "E.22",
        image: "https://placehold.co/600x400.png",
        status: "Da fare",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Chiesa",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "MESSA IN SICUREZZA DEI PROSPETTI DEL FABBRICATO VIAGGIATORI",
        location: "Sassari",
        startDate: "2023-09-01",
        endDate: "2023-09-01",
        client: "RFI",
        service: "Progetto esecutivo",
        amount: 750000,
        category: "E.20",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Stazione",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "MESSA IN SICUREZZA DELL’ABITATO DELLA FRAZIONE SAN VITTORINO",
        location: "Cerro a Volturno (IS)",
        startDate: "2023-09-01",
        endDate: "2023-09-01",
        client: "Comune di Cerro a Volturno",
        service: "Collaudo Sismico",
        amount: 1400000,
        category: "S.04",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Strutture",
        intervention: "Collaudo",
        isPublic: true
    },
    {
        name: "LAVORI DI ACCESSIBILITÀ DELLA STAZIONE DI ORISTANO",
        location: "Oristano",
        startDate: "2023-07-13",
        endDate: "2024-02-13",
        client: "Spinosa costruzioni generali S.p.A.",
        service: "Progetto Esecutivo",
        amount: 0,
        category: "",
        image: "https://placehold.co/600x400.png",
        status: "Da fare",
        works: [],
        description: "",
        classification: "Privati",
        typology: "Stazione",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "PROGETTO DI RISTRUTTURAZIONE STUDIO DENTISTICO",
        location: "Isernia",
        startDate: "2023-06-01",
        endDate: "2023-06-01",
        client: "Dott. Guido Di Marzio",
        service: "Progetto Esecutivo e D.L.",
        amount: 50000,
        category: "",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Privati",
        typology: "Studio",
        intervention: "Interni",
        isPublic: true
    },
    {
        name: "SISTEMAZIONE STRADE INTERNE",
        location: "Capracotta (IS)",
        startDate: "2023-03-01",
        endDate: "2023-06-01",
        client: "Comune di Capracotta",
        service: "Progetto Esecutivo, D.L., C.S.E., C.R.E.",
        amount: 83790.52,
        category: "V.01",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Strade",
        intervention: "Manutenzione",
        isPublic: true
    },
    {
        name: "PROGETTO DI CONSOLIDAMENTO E RESTAURO DELLA CANTORIA DELLA CATTEDRALE DI S. PIETRO APOSTOLO",
        location: "Isernia",
        startDate: "2022-01-11",
        endDate: "2023-02-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo e D.L.",
        amount: 40000,
        category: "E.22",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Chiesa",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "SISTEMAZIONE E MESSA IN SICUREZZA DEL MOVIMENTO FRANOSO DI VIA MAINARDE",
        location: "Capracotta (IS)",
        startDate: "2021-09-01",
        endDate: "2022-02-01",
        client: "Comune di Capracotta",
        service: "Collaudo Tecnico-Amministrativo",
        amount: 400000,
        category: "S.04",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Strutture",
        intervention: "Collaudo",
        isPublic: true
    },
    {
        name: "INTERVENTI DI TUTELA E VALORIZZAZIONE DEI SITI ARCHEOLOGICI - ALLESTIMENTO MUSEALE",
        location: "Pietrabbondante (IS)",
        startDate: "2021-05-01",
        endDate: "2022-09-01",
        client: "Comune di Pietrabbondante",
        service: "Supporto al RUP",
        amount: 600000,
        category: "E.21",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Museo",
        intervention: "RUP",
        isPublic: true
    },
    {
        name: "MANUTENZIONE STRAORDINARIA PROSPETTI E COPERTURA DEL FABBRICATO VIAGGIATORI",
        location: "Borore (NU)",
        startDate: "2021-01-10",
        endDate: "2021-01-10",
        client: "RFI",
        service: "Progetto esecutivo",
        amount: 285000,
        category: "E.20",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Stazione",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "LAVORI DI STRAORDINARIA MANUTENZIONE DEL MUSEO DIOCESANO IN ISERNIA",
        location: "Isernia",
        startDate: "2019-11-01",
        endDate: "2021-10-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo, D.L.",
        amount: 75000,
        category: "E.21",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Museo",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "RESTAURO E RISANAMENTO CONSERVATIVO DELLA CHIESA DI SAN BARTOLOMEO APOSTOLO",
        location: "Longano (IS)",
        startDate: "2019-10-01",
        endDate: "2021-12-01",
        client: "Diocesi di Isernia-Venafro",
        service: "Progetto Esecutivo e D.L.",
        amount: 250000,
        category: "E.22",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Chiesa",
        intervention: "Ristrutturazione",
        isPublic: true
    },
    {
        name: "PROGETTAZIONE ESECUTIVA E LA REALIZZAZIONE DEI LAVORI DI COSTRUZIONE DELL’EDIFICIO SCOLASTICO SEDE DELLA SCUOLA PRIMARIA E SECONDARIA DI PRIMO GRADO",
        location: "Colletorto (CB)",
        startDate: "2009-12-01",
        endDate: "2012-10-01",
        client: "Comune di Colletorto",
        service: "Progetto Preliminare",
        amount: 3008783,
        category: "E.08",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Scuola",
        intervention: "Realizzazione",
        isPublic: true
    },
    {
        name: "RISTRUTTURAZIONE DI FABBRICATO DA DESTINARE AD ASILO NIDO",
        location: "Fornelli (IS)",
        startDate: "2009-05-01",
        endDate: "2012-09-01",
        client: "Comune di Fornelli",
        service: "Progetto Preliminare per Avviso Pubblico, Progetto Esecutivo e D.L.",
        amount: 170000,
        category: "E.20",
        image: "https://placehold.co/600x400.png",
        status: "Completato",
        works: [],
        description: "",
        classification: "Enti pubblici",
        typology: "Scuola",
        intervention: "Ristrutturazione",
        isPublic: true
    }
];

export async function seedProjects() {
    const projectsCollectionRef = collection(db, 'projects');
    const batch = writeBatch(db);

    projectsData.forEach(project => {
        const docRef = doc(projectsCollectionRef);
        
        const projectToSave: Omit<Project, 'id'> = {
            name: project.name || "",
            image: project.image || "https://placehold.co/600x400.png",
            location: project.location || "",
            startDate: project.startDate || new Date().toISOString().split('T')[0],
            endDate: project.endDate || new Date().toISOString().split('T')[0],
            classification: project.classification || "",
            category: project.category || "",
            typology: project.typology || "",
            intervention: project.intervention || "",
            client: project.client || "",
            service: project.service || "",
            amount: project.amount || 0,
            status: project.status || "Da fare",
            works: project.works || [],
            description: project.description || "",
            isPublic: project.isPublic === undefined ? true : project.isPublic,
        };
        batch.set(docRef, projectToSave);
    });

    try {
        await batch.commit();
        console.log('Successfully seeded projects with user data!');
    } catch (error) {
        console.error('Error seeding projects:', error);
        throw error; // Re-throw to be caught by useProjects
    }
}

    